### ISSUE TITLE
建议：将错误码数值设为常量

### ISSUE THREAD

**Issue by aixcyi** [GengGode/GenshinImpact_AutoTrack_DLL#11]
不建议直接使用整数值设置错误码，因为一个整数往往不能让人很快联想到错误原因，并且在错误码变动时可能很难一次性找出所有错误码（毕竟别的地方也会用到数字）。

如果要解决，就不得不在用到错误码的地方打上 **完全相同** 的注释，这样倒不如直接使用常量。

以下是一些常量名称的建议：

| 数值 | 常量名                    | 含义                                     |
| ---- | ------------------------- | ---------------------------------------- |
| `0`  | ERR_SUCCESS               | 执行成功/正常退出。                      |
| `1`  | ERR_UNINITIALIZED         | 未初始化。                               |
| `2`  | ERR_HWND_NO_FOUND         | 未能找到原神窗口句柄。                   |
| `3`  | ERR_EMPTY_SCREEN          | 窗口画面为空。                           |
| `4`  | ERR_NO_KEYPOINT           | 未能匹配到特征点。                       |
| `5`  | ERR_MINIMAP_TOO_SMALL     | 原神小地图区域为空或者区域长宽小于60px。 |
| `6`  | ERR_PAIMON_NO_FOUND       | 未能匹配到派蒙。                         |
| `7`  | ERR_KEYPOINT_OUT_OF_INDEX | 特征点数组访问越界，是个bug。            |
| `8`  | ERR_NO_VALID_UID          | 未能在UID区域检测到有效UID。             |
| `9`  |                           | 提取小箭头特征误差过大。                 |
| `10` | ERR_INVALID_HWND          | 无效句柄或指定句柄所指向窗口不存在。     |
| `11` |                           | 未能取到小箭头区域。                     |
| `12` | ERR_OLDER_HWND            | 窗口句柄失效。                           |

**Comment by GengGode** [comment]
yysy，确实，嗯，你英语真好
![@}OMI5TWEKHOXH7(CVUVGJ9](https://user-images.githubusercontent.com/47711102/124394801-8e92fb80-dd33-11eb-9477-a17f335ce51a.png)

**Comment by GengGode** [comment]
刚才试了下，怎么说呢，很难直接返回字符串Get LastError的时候，只能返回数字的话，emmm，其实可以程序里每一个返回的错误码都不一样，回头可以试下这个，这样就可以直接定位到在哪一行了，回头都试试

**Comment by aixcyi** [comment]
啊这……

我提议的是设置 **全局常量** 而不是用字符串代替数值返回值，也就是说上面英文实际上应该是一个 **变量名** 而不是字符串。

不过我没有学过C++，看了[这篇帖子](https://www.cnblogs.com/wanghetao/p/4492582.html)之后，我猜测应该是在头文件中定义 `static` 修饰的变量：

```C++
static int ERR_SUCCESS = 0;    // 执行成功/正常退出。
static int ERR_UNINITIALIZED = 1;    // 未初始化。
static int ERR_HWND_NO_FOUND = 2;    // 未能找到原神窗口句柄。
static int ERR_EMPTY_SCREEN = 3;    // 窗口画面为空。
// 省略...
```

然后应该就能在其它代码文件中使用了。

**Comment by GengGode** [comment]
一般来讲都是使用宏定义
‘’‘C++
#define ERR_SUCCESS 0
’‘’
这样，emmm，但是怎么说呢，这个程序的体量还没必要用到，如果要改进的话最好是能够直接获得到有效的信息比如字符，我会构造一个类或者函数去实现这个。
另外你Python的调用成功了吗，能不能把例子上传上来b（￣▽￣）d

**Comment by aixcyi** [comment]
嗯。但，也许对于你来说这个体量并不大，但对于一个多人协作的开源项目来说，这一点还是很有必要的，毕竟我第一次就是看不懂（逃

Python代码还在写，明天估计能测试完。不过毕竟连上线的时间都没多少，就更别提这个了。（来自打工人的捂脸）

**Comment by GengGode** [comment]
在做了在做了，准备又加了新的接口，getLastErrStr（），返回一个const char* 字符串指针，不知道能不能传出这样的参数类型，一边重构一边维护老的版本，这就是多人协作吗
![image](https://user-images.githubusercontent.com/47711102/124499957-771a4800-ddf1-11eb-87ec-501e9b9aaf91.png)
同样的打工人，明天北京出差

**Comment by GengGode** [comment]
我在refactxx重构分支里添加了这个功能，根据使用来看我或许可以直接让他输出指定位置的文字说明，通过传入要执行函数的指针以及一个错误信息，目前还是错误码，这样当这个函数执行失败的时候就可以通过getLastErrStr来看到错误信息了

**Comment by GengGode** [comment]
![image](https://user-images.githubusercontent.com/47711102/124679955-fbef8980-def7-11eb-99fa-035f26ca60ff.png)

**Comment by aixcyi** [comment]
( ⊙ o ⊙ )啊？这是？

**Comment by GengGode** [comment]
重构了，但没完全重构

**Comment by aixcyi** [comment]
对了，忘记说一声记得写一下这dll的调用方式是stdcall还是cdecl了，现在才想起来。

issue：聊天？那我走？

**Comment by aixcyi** [comment]
啊这？我又不学C++，我哪儿知道呀（捂脸

issue：啊那我睡了。

**Comment by GengGode** [comment]
算了都一样吧，都一样
issue已死，有事烧纸

**Comment by GengGode** [comment]
是stdcall，cpp里写了，才发现
