### ISSUE TITLE
获取坐标是什么原理

### ISSUE THREAD

**Issue by xavieryang007** [GengGode/GenshinImpact_AutoTrack_DLL#17]
游戏中没有坐标，可以讲下计算坐标原理吗

**Comment by GengGode** [comment]
图像匹配算法SURF，根据小地图和大地图做匹配得到
![$R18WXBENU79PHR5NFEIQUJ](https://user-images.githubusercontent.com/47711102/144619565-ba14b8ad-f283-4246-8bba-11719d832bd7.jpg)
，
