### ISSUE TITLE
可以参考一下我这个项目的思路

### ISSUE THREAD

**Issue by fourquadrantlogger** [GengGode/GenshinImpact_AutoTrack_DLL#20]
用c#实现了抓屏功能，但是以http接口对外提供服务，单独抽出了抓拍功能，把图像分析的算法代码，放在python+web等语言中完成

https://github.com/timeloveboy/genshinstatus

**Comment by GengGode** [comment]
404了？
图像算法用cpp效率更高一些，所以Core肯定是cpp的，但是cpp做网络太麻烦了，就没搞，现在已经基本适应大部分环境了，之后可以再加一个传入图片字节的接口，就可以外部传入图片了
类似 
```
bool GetInfoFromBitmap(void* bitmap,int size , ... );
```
