### ISSUE TITLE
无法追踪角色

### ISSUE THREAD

**Issue by linqlpnil** [GengGode/GenshinImpact_AutoTrack_DLL#21]
![QQ截图20220528133302](https://user-images.githubusercontent.com/40204716/170811643-37f8555b-ee6b-45bd-a30f-c28f006d1fd3.png)

**Comment by linqlpnil** [comment]
另，能否将logo做小一点（或随窗口大小变化而变化）

**Comment by GengGode** [comment]
因为有一个引导需要做但是我还没时间搞，logo大小可以调整，也得等我有空了，现在这份工作太忙了，等到7.12号之后我不忙了就挨个更新

**Comment by GengGode** [comment]
现在最新的可以了，但是商店可能还在审核更新，昨天推送的，可以在商店检查下更新
