### ISSUE TITLE
1366x768不能运行

### ISSUE THREAD

**Issue by huizichin** [GengGode/GenshinImpact_AutoTrack_DLL#22]
https://github.com/YuehaiTeam/frostflake/issues/1

autoTrack.log
https://gist.github.com/huizichin/fcf0047132393596c101fbd8772b449b

**Comment by huizichin** [comment]
试了试私人服务器，改了点启动名字去YuanShen.exe就能了。
![image](https://user-images.githubusercontent.com/16850884/172019584-b98d5246-2350-47ff-94ac-14cc38998664.png)
看来是不支持国际服务器
![image](https://user-images.githubusercontent.com/16850884/172019620-b5b74360-9a0f-462f-a10b-d0659cda76ee.png)
因为国际服务器是GenshinImpact.exe不是YuanShen.exe。有什么办法吗？

**Comment by huizichin** [comment]
![image](https://user-images.githubusercontent.com/16850884/172029306-f0afab90-4d7a-4367-bae8-12b6898d22fe.png)
但是我不太明白，为什么GenshinImpact.exe就是不能操作呢？我试了华文和英文，都不能。虽然这里只是看Windows的名字

**Comment by huizichin** [comment]
终于找到问题了，分辨率1366x768不能运行。
跳去1280x720就能了

**Comment by GengGode** [comment]
奇怪，emmm可以查看下“Genshin”和“Impact”间是否存在空格，此前是有一个setHandle接口，支持外部传入原神handle，但是目前悬浮窗和椰羊都没做获取句柄的功能
1366x768应该是没问题的啊，我再测试测试，有一定概率是分辨率低了之后识别率低了导致的吧
如果1366x768是全屏模式的话，可能是全屏和普通窗口的一些差异导致的，可以下载运行下https://gitee.com/Yu_Sui_Xian/GenshinImpact_AutoMap/attach_files/1086541/download/Release.zip
运行后检查是否识别到uid，以及Alt+M键获取运行中截图，检查截图是否存在透明通道。

希望能得到反馈，谢谢

**Comment by GengGode** [comment]
不好意思，刚刚看到原消息，这个大概率是由于使用的dll不是最新版导致的，之前问了椰羊，他还没用最新版的dll，应该最近会推送
