### ISSUE TITLE
使用手柄时效果变差

### ISSUE THREAD

**Issue by zdtyuiop4444** [GengGode/GenshinImpact_AutoTrack_DLL#23]
切换成手柄控制的时候定位会明显的开始不准，推测是因为手柄控制时界面UI比例缩小

**Comment by GengGode** [comment]
并没有做手柄的适配，需要改些地方，7月份就会改好的，如果这个月工作不忙的话，这个月也能搞定
一开始没用过手柄，做的思路没考虑两种布局的情况，难顶

**Comment by GengGode** [comment]
6.5.38版本已适配手柄
