### ISSUE TITLE
须弥地图跟踪什么时候能支持？

### ISSUE THREAD

**Issue by d13187** [GengGode/GenshinImpact_AutoTrack_DLL#26]

**Comment by Bilx-ZL** [comment]
看起来是个弃坑项目

**Comment by GengGode** [comment]
都支持的，在改地图了，emmm这两天就改出来了

**Comment by GengGode** [comment]
已经做好了，文档还没改，但是接口没变

**Comment by GengGode** [comment]
> 层岩巨渊地下都还没支持,估计还远

也是支持的，但是要调用GetPostionOfMap获取地图所属id,只调用getPostion默认出来的是提瓦特的

**Comment by pansx** [comment]
唔,我和楼主都是用志琼的,估计是志琼没做适配吧...
