### ISSUE TITLE
check_paimon在有新消息红点时匹配失败，返回1000

### ISSUE THREAD

**Issue by naiteluo** [GengGode/GenshinImpact_AutoTrack_DLL#31]
https://github.com/GengGode/GenshinImpact_AutoTrack_DLL/blob/173d3c2476e8a6b35f4b42f36390f02c1cbf8f3e/cvAutoTrack/src/AutoTrack.cpp#L246

resource中使用的paimon图标是默认状态下的图标，有新邮件或新推送内容的时候，paimon图标右上角会有红点（下图的位置），此时无法正确检测到paimon。直接返回错误码1000。

可以考虑做两种状态下的paimon图标的检测，或者只对不含红点的左半或下半部分区域做检查，效率会更高。

![image](https://user-images.githubusercontent.com/705655/191928884-f663b9d7-3ed6-4fbf-86f2-a847f6f76616.png)

**Comment by naiteluo** [comment]
如果没有时间修改的话可以大概说一下改动建议，我这边会尝试修改提pr

**Comment by GengGode** [comment]
emmm，之前是可以的，这是因为修改了匹配的阈值，把阈值减低一些就可以了
这个的话，我先把Dxgi的截图做出来再来改这个阈值，Dx截图的结果跟现在的结果有一些差异，需要重新测试下阈值

**Comment by GengGode** [comment]
已经修复
