### ISSUE TITLE
定位存在误差

### ISSUE THREAD

**Issue by GengGode** [GengGode/GenshinImpact_AutoTrack_DLL#46]
![WM02L{V 2A~D$V}1TNTJ 7P](https://user-images.githubusercontent.com/47711102/194566839-85b07de8-07ea-4600-98b4-4d6c2f5d98c8.png)
![QOUNRDNL 9~FX 2US~(7AD3](https://user-images.githubusercontent.com/47711102/194566871-2c381598-f41a-4eb6-b6d2-eec159047065.png)
经过观察，普遍存在一个偏上的误差，暂不清楚原因

**Comment by infstellar** [comment]
好像定位的时候坐标输出会有一个误差逐渐减小的过程？（版本6.2）

**Comment by GengGode** [comment]
内部走了卡尔曼滤波，所以误差会逐渐减小
