### ISSUE TITLE
版本输出好像有问题

### ISSUE THREAD

**Issue by pboymt** [GengGode/GenshinImpact_AutoTrack_DLL#48]
现在应该是 `7.0` 了吧，但是调用 `version()` 这个方法检查版本的时候输出还是`6.4.1`

**Comment by GengGode** [comment]
没完全修好
编译版本号会有偏差，原因是编译版本号来自AppVeyor平台，暂时没有编译前获取方案
目前只能从git tag中获取最后一个tag版本，然后对其编译版本号+1。
但是这样会与实际的编译版本号有差异，实际编译版本号应该会大于等于dll中打包进去的版本号
因为每一次在分支进行的远程编译也会导致编译版本号的增加， 但是并不会更新tag。

解决方案是不在记录编译版本号，而是显示 x.x.x-编译分支-commit hash

**Comment by pboymt** [comment]
你可以看下  [flunyaa](https://github.com/flunyaa/flunyaa) 里面的ps1脚本，项目本地弄一个版本号文件，然后每次打tag之前增加一下比较好。
