### ISSUE TITLE
是否可以新增一个合并接口提高效率？

### ISSUE THREAD

**Issue by naiteluo** [GengGode/GenshinImpact_AutoTrack_DLL#57]
- GetTransformOfMap
- GetPositionOfMap
- GetDirection
- GetRotation

在常规场景中可能需要同时获取上面几个接口的返回信息，而这几个接口如果都需要额外进行截图的话，会有额外的截图消耗。组合成一个新接口一次性返回位置和朝向信息，使用上更方便，同时是否有效率的提升？

**Comment by GengGode** [comment]
计划是有一个
``` c++
GetAvatarInfo(
  int uid,
  double x,
  double y,
  double a,
  double a2,
  int map_id
)
```
或者是内部能够复用之前的截图。
之所以分开是因为position的运行时间要远比其他的长，就考虑视角角度之类的调用频率可以高一点，实时性更好。
晚上加这个接口吧，复用截图未免会有副作用。

**Comment by GengGode** [comment]
寄了。今天pc连不上git

**Comment by naiteluo** [comment]
不急，按自己节奏来，辛苦了

**Comment by GengGode** [comment]
已经推送了，GetAllInfo
