### ISSUE TITLE
v7以上版本的函数调用

### ISSUE THREAD

**Issue by infstellar** [GengGode/GenshinImpact_AutoTrack_DLL#67]
在py调用的时候报错
function 'GetTransform' not found
function 'GetPosition' not found
是函数API更新了吗(・◇・)？

**Comment by GengGode** [comment]
是的，请看下函数列表，该接口已经删除了
改为了 GetTransformOfMap ...
因为出现了几个不同的地图区域 地下层岩和渊下宫等
python的样例好像忘改了（

**Comment by infstellar** [comment]
emm 但有时只要获得角度，同时获得坐标的话开销很大awa

**Comment by GengGode** [comment]
有啊
![image](https://user-images.githubusercontent.com/47711102/199012971-6b41b226-21a7-452a-b32b-898476c46783.png)

**Comment by infstellar** [comment]
> 有啊 ![image](https://user-images.githubusercontent.com/47711102/199012971-6b41b226-21a7-452a-b32b-898476c46783.png)
啊这 前几天好像看漏了 |･ω･｀)
