### ISSUE TITLE
拼写错误（？）

### ISSUE THREAD

**Issue by infstellar** [GengGode/GenshinImpact_AutoTrack_DLL#84]
函数 verison 应该是 version 吧⊙(・◇・)？

**Comment by GengGode** [comment]
草，确实是（

**Comment by GengGode** [comment]
8.0.0的时候删掉它就好了（
这个接口已经不用了，换了更安全的`GetCompileVersion`（这回是对的了

**Comment by infstellar** [comment]
okok 我就说为什么py调用version接口总是返回空

**Comment by GengGode** [comment]
估计是指针的问题，这个接口有问题，别用了（忘了标注待删除了

**Comment by infstellar** [comment]
vscode默认没有拼写检查 我拼错重命名可费劲了 (
