### ISSUE TITLE
建议：在 `README` 中注明哪些函数需要初始化

### ISSUE THREAD

**Issue by aixcyi** [GengGode/GenshinImpact_AutoTrack_DLL#9]
### 背景
我正在尝试编写Python代码使用该DLL（release），但调用 `GetUID` 函数时出现以下报错。
```plain
[WinError -529697949] Windows Error 0xe06d7363
```
因为我的电脑同时运行着火狐浏览器、PyCharm以及原神，内存占用达到了82%，只剩不到1GB可用，同时我觉得使用 `GetUID` 前应该不需要调用 `init` 进行初始化，加之 `README` 中介绍 `init` 占用峰值会达到1GB，因此我事先并没有调用 `init` 。

### 建议
在 `README` 中注明哪些函数需要初始化。

**Comment by GengGode** [comment]
Emmm只有位置需要，别的都不需要，GetTrf的那个内部自动初始化，实际上也不需要手动初始化。

**Comment by GengGode** [comment]
关于保存？有没有更详细的日志，或者我尝试编译debug版发布，以便查看输出日志

**Comment by aixcyi** [comment]
好吧，不得不说这是一个奇怪的bug。

因为GetUID是一个看起来比较容易拿捏的函数，所以我第一次就是调用的它，但撞板后我开始尝试其它函数，包括那个会自动调用初始化的GetTransform。

一开始我的顺序是GetLastErr、GetUID、GetTransform。
GetLastErr正常返回0，执行到GetUID时报错，错误一如上面的问题所提到的那样，然后程序的执行被终止。

然而当我改变顺序，变为调用GetLastErr、GetTransform、GetUID后，它居然能正常获取到我的UID了！

然后我把调用顺序改回GetLastErr、GetUID、GetTransform，再执行却没有报错。

所以我有理由怀疑GetUID实际上是需要初始化的，或者说在不经意的地方调用了需要初始化的代码。

另外，在测试时我全屏运行原神，时间是晚上，地点是低语森林，然后不打开任何面板的情况化，延时5秒依次调用GetUID、GetDirection、GetTransform、GetPosition，其中前后两个都能成功，而中间两个失败，错误都是 `6 - 未能匹配到派蒙` 。

附上我的Python代码
```Python
from ctypes import c_int, c_bool, POINTER, CDLL, c_double, c_float
from time import sleep

sleep(5)

lib = CDLL(r'./CVAUTOTRACK.dll')
print('Last error is', lib.GetLastErr(), '\n')

lib.GetUID.argtypes = [POINTER(c_int)]
lib.GetUID.restype = c_bool
uid = c_int(0)
ret = lib.GetUID(uid)
print(ret, uid.value)
print('Last error is', lib.GetLastErr(), '\n')

lib.GetDirection.argtypes = [POINTER(c_double)]
lib.GetDirection.restype = c_bool
a = c_double(0)
ret = lib.GetDirection(a)
print(ret, a.value)
print('Last error is', lib.GetLastErr(), '\n')

lib.GetTransform.argtypes = [POINTER(c_float), POINTER(c_float), POINTER(c_float)]
lib.GetTransform.restype = c_bool
x, y, a = c_float(0), c_float(0), c_float(0)
ret = lib.GetTransform(x, y, a)
print(ret, x.value, y.value, a.value)
print('Last error is', lib.GetLastErr(), '\n')

lib.GetPosition.argtypes = [POINTER(c_float), POINTER(c_float)]
lib.GetPosition.restype = c_bool
x, y = c_float(0), c_float(0)
ret = lib.GetPosition(x, y)
print(ret, x.value, y.value)
print('Last error is', lib.GetLastErr(), '\n')
```
以及输出结果
```plain
Last error is 0

True 我的UID
Last error is 0

False 0.0
Last error is 6 

False 0.0 0.0 0.0
Last error is 6 

True 0.0 0.0
Last error is 0 
```

最后，顺路墙裂建议一下，在编译DLL前写上版本号属性。毕竟从近期的邮件看，这个项目迭代太快了，以至于我想附上我所用的DLL的版本，都不知道该写什么。(っ*´Д`)っ

**Comment by GengGode** [comment]
关于GetUID，我们进行了一定的测试，发现当分辨不是1920*1080时，由于某些原因（截取的图片区域小了，对应不上了），会导致直接崩溃，版本号，可以加，但是调用的时候要改dll的名称，就没加。迭代都是假的，因为用的自动构建，我改个readme他都会构建一版[笑哭]，都没啥大改动，至少接口都没动

**Comment by GengGode** [comment]
派蒙没有匹配上的话基本可以确定原因是分辨率不适配

**Comment by GengGode** [comment]
![image](https://user-images.githubusercontent.com/47711102/124293723-8a2adf00-db89-11eb-9360-0761189ce0fc.png)
GetUID内部确实不需要初始化，做了几个判断之后就在红框里进行的识别算法，这个算法在某些情况下会直接导致闪退，主要是templateMatch函数所需的图片大小不一致导致的，这一块还在优化。

**Comment by aixcyi** [comment]
然鹅……我的就是1920x1080，全局缩放是125%，用了lively动态壁纸但应该不影响才对。

**Comment by GengGode** [comment]
全局缩放是125%可会有影响，我忘了测试的时候有没有测这个了，然后原神抗锯齿要开SAMM

**Comment by aixcyi** [comment]
那顺便测试一下TAM吧。似乎原神默认是这个抗锯齿算法。

**Comment by GengGode** [comment]
不行的，截图的话，透明通道就没了，只有SAMM才能截到透明通道，这样就没有背景景物的干扰了，只有UI界面

**Comment by aixcyi** [comment]
怪不得。那应该在`README`里注明呀~(ノ-_-)ノ~┻━┻

**Comment by GengGode** [comment]
麻了，忘掉了/(ㄒoㄒ)/

**Comment by aixcyi** [comment]
那明天我帮忙整理一下`README`吧，顺便试一下提交Pull Request是什么感觉。(￣▽￣)～■干杯□～(￣▽￣)

**Comment by GengGode** [comment]
好啊，(￣▽￣)～■干杯□～(￣▽￣)

**Comment by aixcyi** [comment]
抱歉，我实在是克隆不了源代码。无论用什么方式调用，git总是会停在 `65% (409/628), x.xx MiB | 8.00 KiB/s`（图片太大），除非手动下载zip包。然而即使是手动下载zip包，git也需要克隆一遍代码才能设置跟踪分支。建议在码云（gitee.com）也开一个仓库吧。

**Comment by GengGode** [comment]
我麻了，应该是原神地图，那是一张45MB的大图，我有在gitee上开，就在

https://gitee.com/Yu_Sui_Xian/yuanshen-auto-tracking-dll

或许有方法可以克隆的时候不克隆大文件，或者是设置可以克隆大文件，我的天，头大

**Comment by GengGode** [comment]
git clone http://github.com/large-repository --depth 1
cd large-repository
git fetch --unshallow
可以浅克隆，然后之后再在IDE里拉取

**Comment by aixcyi** [comment]
emmm，经过漫长的等待（其实是打游戏打到那么晚つ﹏⊂），我终于克隆完了。╰(￣▽￣)╭

我是先建了个本地空仓库，然后设置远程仓库，接着尝试用PyCharm更新项目，等它用8KiB/s的速度下完……就好了。
┗|｀O′|┛ 嗷~~

**Comment by GengGode** [comment]
PyCharm可还行Σ(っ °Д °;)っ。我这个是用的VS开发的，然后编译得话需要用到opencv4.5.0的静态链接库，在另一个库里。不编译得话就没啥了
